[llm]
model = "llama3.2:latest"
api_key = ""  # No API key needed for Ollama
base_url = "http://localhost:11434/v1/chat/completions"
max_tokens = 4096
temperature = 0.8

[chunking]
chunk_size = 100  # Number of words per chunk
overlap = 20      # Number of words to overlap between chunks

[standardization]
enabled = true             # Whether to enable entity standardization
use_llm_for_entities = true  # Whether to use LLM for additional entity resolution

[inference]
enabled = true             # Whether to enable relationship inference
use_llm_for_inference = true  # Whether to use LLM for relationship inference
apply_transitive = true    # Whether to apply transitive inference rules

[visualization]
edge_smooth = false  # Options: false, "dynamic", "continuous", "discrete", "diagonalCross", 
                         # "straightCross", "horizontal", "vertical", "curvedCW", "curvedCCW", "cubicBezier": true = "continuous"
